# Generated by Django 5.1.7 on 2025-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_remove_application_applied_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
